import { createElement } from 'react'
import { renderToStaticMarkup } from 'react-dom/server'
import { describe, expect, it } from 'vitest'

import { BriefScreen } from '../src/components/brief-screen'
import { type DailyBrief } from '../src/domain/brief'
import { dailyBriefFixture } from './fixtures/market'

function render(latest: DailyBrief | undefined): string {
  return renderToStaticMarkup(createElement(BriefScreen, { latest, onSymbol: () => undefined }))
}

describe('the brief screen', () => {
  it('shows the trade line, the direction, the rendered thesis, and the reading list', () => {
    const html = render(dailyBriefFixture)
    expect(html).toContain('Buy NVDA 205c 10/16/26')
    expect(html).toContain('bullish')
    expect(html).toContain('<strong>Catalyst:</strong> demand checks keep the AI capex case alive.')
    expect(html).toContain('<li>IV rank 22, options are cheap.</li>')
    expect(html).toContain('href="https://www.reuters.com/markets/us/capex-2026"')
    expect(html).toContain('www.reuters.com')
    expect(html).toContain('Generated by <strong>@cf/zai-org/glm-5.3</strong>')
    expect(html).toContain('Not financial advice.')
    expect(html).toContain('Previous')
  })

  it('renders model markup as text, never as HTML', () => {
    const html = render({
      ...dailyBriefFixture,
      recommendations: [{ ...dailyBriefFixture.recommendations[0]!, thesis: '<img src=x onerror=alert(1)> and [x](javascript:alert(1))' }],
    })
    expect(html).toContain('&lt;img src=x onerror=alert(1)&gt;')
    expect(html).not.toContain('href="javascript:')
    expect(html).toContain('[x](javascript:alert(1))')
  })

  it('says so when nothing has been published', () => {
    const html = render(undefined)
    expect(html).toContain('No brief yet')
    expect(html).not.toContain('Previous')
  })
})
