import { createElement } from 'react'
import { renderToStaticMarkup } from 'react-dom/server'
import { describe, expect, it } from 'vitest'

import { briefAge, RecommendationScreen } from '../src/components/recommendation-screen'
import { type DailyRecommendations } from '../src/domain/market'
import { marketSnapshotFixture } from './fixtures/market'

const PUBLISHED_AT = '2026-08-13T13:35:00.000Z'

function render(dailyRecommendations: DailyRecommendations | undefined, now: Date): string {
  return renderToStaticMarkup(createElement(RecommendationScreen, {
    availableSymbols: new Set(['NVDA']),
    dailyRecommendations,
    now,
    onSymbol: () => undefined,
  }))
}

describe('recommendation availability', () => {
  it('shows only the provenance note for a brief that published nothing', () => {
    const latest = marketSnapshotFixture().recommendations!
    const dailyRecommendations = {
      ...latest,
      recommendations: [],
      links: [],
      regime: 'Weekend event screen',
      regimeDetail: 'Aug 29 2026 weekend; next session Aug 31.',
      summary: 'Investigating weekend catalysts before ranking.',
    }
    const html = render(dailyRecommendations, new Date('2026-08-29T12:00:00.000Z'))

    expect(html).toContain('About this brief')
    expect(html).toContain('Previous')
    expect(html).not.toContain('Weekend event screen')
    expect(html).not.toContain('Investigating weekend catalysts')
    // Nothing on the site promises a run at a time of day any more.
    expect(html).not.toContain('Next research run')
  })

  it('says so when nothing has ever been published', () => {
    const html = render(undefined, new Date('2026-08-29T12:00:00.000Z'))
    expect(html).toContain('No brief yet')
    // Nothing on the site offers to produce one: generation lives elsewhere.
    expect(html).not.toContain('Connect')
  })

  it('shows completed research with the model that produced it', () => {
    const dailyRecommendations = { ...marketSnapshotFixture().recommendations!, model: 'claude-opus-5' }
    const html = render(dailyRecommendations, new Date('2026-08-29T12:00:00.000Z'))

    expect(html).toContain('Selective long vol')
    expect(html).toContain('Demand checks keep the AI capex case alive')
    expect(html).toContain('Not financial advice.')
    expect(html).toContain('Generated by <strong>claude-opus-5</strong>')
    expect(html).toContain('15 days ago')
  })

  it('credits the product, not a powered-by marketing line', () => {
    const dailyRecommendations = {
      ...marketSnapshotFixture().recommendations!,
      model: 'Muse Code powered by Meta Muse Spark',
    }
    const html = render(dailyRecommendations, new Date('2026-08-29T12:00:00.000Z'))
    expect(html).toContain('Generated by <strong>Muse Code</strong>')
    expect(html).not.toContain('Meta Muse Spark')
  })

  it('credits the publisher by the handle they chose, and nothing else about them', () => {
    const dailyRecommendations = {
      ...marketSnapshotFixture().recommendations!,
      byline: 'volhound',
      model: 'claude-opus-5',
    }
    const html = render(dailyRecommendations, new Date('2026-08-29T12:00:00.000Z'))
    expect(html).toContain('Generated by <strong>claude-opus-5</strong>')
    expect(html).toContain('published by <strong>volhound</strong>')
  })

  it('shows nothing for a publisher on a brief that named none', () => {
    const dailyRecommendations = { ...marketSnapshotFixture().recommendations!, model: 'claude-opus-5' }
    expect(render(dailyRecommendations, new Date('2026-08-29T12:00:00.000Z'))).not.toContain('published by')
  })

  it('marks a recommendation its own sources no longer support, with the reasons', () => {
    const latest = marketSnapshotFixture().recommendations!
    const dailyRecommendations = {
      ...latest,
      recommendations: latest.recommendations.map((recommendation, index) => index === 0
        ? {
            ...recommendation,
            verification: {
              checkedAt: '2026-08-29T11:00:00.000Z',
              reasons: ['quote no longer in https://example.com/announcement: "demand remains durable"'],
              status: 'stale' as const,
            },
          }
        : recommendation),
    }
    const html = render(dailyRecommendations, new Date('2026-08-29T12:00:00.000Z'))
    expect(html).toContain('No longer supported by its sources')
    expect(html).toContain('quote no longer in https://example.com/announcement')
  })

  it('keeps a recheck that held to a quiet line', () => {
    const latest = marketSnapshotFixture().recommendations!
    const dailyRecommendations = {
      ...latest,
      recommendations: latest.recommendations.map((recommendation, index) => index === 0
        ? {
            ...recommendation,
            verification: { checkedAt: '2026-08-29T11:00:00.000Z', reasons: [], status: 'holds' as const },
          }
        : recommendation),
    }
    const html = render(dailyRecommendations, new Date('2026-08-29T12:00:00.000Z'))
    expect(html).toContain('Sources re-checked')
    expect(html).not.toContain('No longer supported')
  })

  it('says so when a brief predates the model being recorded', () => {
    const html = render(marketSnapshotFixture().recommendations!, new Date('2026-08-29T12:00:00.000Z'))
    expect(html).toContain('Model not recorded')
    expect(html).toContain('the model was not recorded')
  })

  it('renders reader links with title, description, and an optional preview image', () => {
    const dailyRecommendations = {
      ...marketSnapshotFixture().recommendations!,
      links: [{
        description: 'The primary announcement and its dated terms.',
        previewImageUrl: 'https://images.example.com/announcement.jpg',
        title: 'Primary announcement',
        url: 'https://example.com/announcement',
      }],
    }
    const html = render(dailyRecommendations, new Date('2026-08-29T12:00:00.000Z'))

    // The list names itself; the heading stays for heading navigation but is not drawn.
    expect(html).toMatch(/<h2[^>]*sr-only[^>]*>Links<\/h2>/)
    expect(html).toContain('Primary announcement')
    expect(html).toContain('The primary announcement and its dated terms.')
    expect(html).toContain('src="https://images.example.com/announcement.jpg"')
    expect(html).toContain('referrerPolicy="no-referrer"')
  })

  it('states age in the unit a reader would use', () => {
    const published = new Date(PUBLISHED_AT)
    expect(briefAge(new Date(published.getTime() + 30_000), PUBLISHED_AT)).toBe('just now')
    expect(briefAge(new Date(published.getTime() + 60_000), PUBLISHED_AT)).toBe('1 minute ago')
    expect(briefAge(new Date(published.getTime() + 3 * 3_600_000), PUBLISHED_AT)).toBe('3 hours ago')
    expect(briefAge(new Date(published.getTime() + 2 * 86_400_000), PUBLISHED_AT)).toBe('2 days ago')
  })
})
