import { z } from 'zod'

import { EquitySymbolSchema } from './instrument'

/**
 * The maintained D1 list, public projection, and snapshot fetch are one product
 * surface. Sharing that invariant prevents a narrower model or browser schema from
 * silently dropping symbols accepted by the authoritative list. The list grows on
 * its own as searches and research admit names, so this is an observable ceiling
 * rather than a curated size: pruning back to a working set stays available for
 * the day the list outgrows what a reader can scan.
 */
export const MAX_WATCHLIST_SYMBOLS = 500

/**
 * The live feed is the one surface the list size cannot carry: every symbol here is
 * an open DXLink subscription in one browser. The rest of the list still renders from
 * the snapshot, so a longer watchlist costs streamed rows rather than visible ones.
 */
export const MAX_LIVE_STREAM_SYMBOLS = 100

const WatchlistSymbolsSchema = z.array(EquitySymbolSchema).min(1).max(MAX_WATCHLIST_SYMBOLS)

/** Heston maintains one internal watchlist; broker list names are seed provenance, not mutation targets. */
export const AddWatchlistSymbolsSchema = z.strictObject({
  kind: z.literal('add_watchlist_symbols'),
  symbols: WatchlistSymbolsSchema,
})
export const RemoveWatchlistSymbolsSchema = z.strictObject({
  kind: z.literal('remove_watchlist_symbols'),
  symbols: WatchlistSymbolsSchema,
})
export const WatchlistMutationSchema = z.discriminatedUnion('kind', [
  AddWatchlistSymbolsSchema,
  RemoveWatchlistSymbolsSchema,
])

export type WatchlistMutation = z.infer<typeof WatchlistMutationSchema>

export const WatchlistMutationResultSchema = z.strictObject({
  appliedSymbols: z.array(EquitySymbolSchema).max(MAX_WATCHLIST_SYMBOLS),
  // This is generated by Heston and may enumerate the complete maintained list.
  detail: z.string().min(1),
  discardedSymbols: z.array(EquitySymbolSchema).max(MAX_WATCHLIST_SYMBOLS),
})

export type WatchlistMutationResult = z.infer<typeof WatchlistMutationResultSchema>
