import { z } from 'zod'

import { EquitySymbolSchema } from './instrument'

/**
 * The maintained D1 list, public projection, snapshot fetch, and live feed are one
 * 100-symbol product surface. Sharing that invariant prevents a narrower model or
 * browser schema from silently dropping symbols accepted by the authoritative list.
 */
export const MAX_WATCHLIST_SYMBOLS = 100

const WatchlistSymbolsSchema = z.array(EquitySymbolSchema).min(1).max(MAX_WATCHLIST_SYMBOLS)

/** Spice maintains one internal watchlist; broker list names are seed provenance, not mutation targets. */
export const AddWatchlistSymbolsSchema = z.strictObject({
  kind: z.literal('add_watchlist_symbols'),
  symbols: WatchlistSymbolsSchema,
})
export const RemoveWatchlistSymbolsSchema = z.strictObject({
  kind: z.literal('remove_watchlist_symbols'),
  symbols: WatchlistSymbolsSchema,
})
export const WatchlistMutationSchema = z.discriminatedUnion('kind', [
  AddWatchlistSymbolsSchema,
  RemoveWatchlistSymbolsSchema,
])

export type WatchlistMutation = z.infer<typeof WatchlistMutationSchema>

export const WatchlistMutationResultSchema = z.strictObject({
  appliedSymbols: z.array(EquitySymbolSchema).max(MAX_WATCHLIST_SYMBOLS),
  // This is generated by Spice and may enumerate the complete maintained list.
  detail: z.string().min(1),
  discardedSymbols: z.array(EquitySymbolSchema).max(MAX_WATCHLIST_SYMBOLS),
})

export type WatchlistMutationResult = z.infer<typeof WatchlistMutationResultSchema>
