import { useState } from 'react'
import { ArrowUpRight, ChevronLeft, ChevronRight } from 'lucide-react'

import { Alert, AlertDescription, AlertTitle } from '#/components/ui/alert'
import { Button } from '#/components/ui/button'
import { Spinner } from '#/components/ui/spinner'
import { loadPreviousDailyBrief } from '../data/brief-archive'
import { type DailyBrief } from '../domain/brief'
import { issueDate, RecommendationCard } from './brief-card'
import { ChannelArchiveScreen } from './channel-archive-screen'

function BriefNavigation({ index, loading, onNewer, onOlder, olderDisabled }: {
  index: number
  loading: boolean
  onNewer: () => void
  onOlder: () => void
  olderDisabled: boolean
}) {
  return (
    <nav aria-label="Brief archive" className="brief-navigation">
      <Button disabled={olderDisabled || loading} onClick={onOlder} size="sm" type="button" variant="ghost">
        {loading ? <Spinner data-icon="inline-start" /> : <ChevronLeft data-icon="inline-start" />}
        Previous
      </Button>
      {index > 0 && (
        <Button disabled={loading} onClick={onNewer} size="sm" type="button" variant="ghost">
          Next<ChevronRight data-icon="inline-end" />
        </Button>
      )}
    </nav>
  )
}

function BriefIssue({ brief, onSymbol }: { brief: DailyBrief; onSymbol: (symbol: string) => void }) {
  return (
    <>
      <header className="brief-cover">
        <time dateTime={brief.publishedAt}>{issueDate.format(new Date(brief.publishedAt))}</time>
        <p className="brief-byline">Generated by <strong>{brief.model}</strong></p>
      </header>
      {brief.links.length > 0 && (
        <section aria-labelledby="brief-links-title" className="brief-links-section">
          <h2 id="brief-links-title">Reading</h2>
          <ol className="brief-links">
            {brief.links.map((link) => (
              <li key={link.url}>
                <a href={link.url} rel="noreferrer" target="_blank">
                  <span>{new URL(link.url).host}</span>{link.url}<ArrowUpRight aria-hidden="true" />
                </a>
              </li>
            ))}
          </ol>
        </section>
      )}
      <section aria-labelledby="brief-trades-title" className="brief-trades">
        <h2 id="brief-trades-title">{brief.recommendations.length ? 'Trades' : 'No trades today'}</h2>
        {brief.recommendations.map((recommendation, index) => (
          <RecommendationCard key={`${recommendation.symbol}-${index}`} onSymbol={onSymbol} recommendation={recommendation} />
        ))}
        <p className="disclaimer">Not financial advice.</p>
      </section>
    </>
  )
}

/**
 * The latest brief with the archive behind it, one issue at a time. Nothing on the site
 * produces a brief: the private Workflow publishes it into the store this reads from.
 */
export function BriefScreen({ latest, onSymbol }: { latest?: DailyBrief; onSymbol: (symbol: string) => void }) {
  const [history, setHistory] = useState<DailyBrief[]>(() => latest ? [latest] : [])
  const [index, setIndex] = useState(0)
  const [archiveEnd, setArchiveEnd] = useState(!latest)
  const [archiveError, setArchiveError] = useState<string>()
  const [loading, setLoading] = useState(false)
  const current = history[index]

  const openOlder = async () => {
    if (history[index + 1]) {
      setIndex(index + 1)
      return
    }
    if (!current) return
    setArchiveError(undefined)
    setLoading(true)
    try {
      const previous = await loadPreviousDailyBrief(current.publishedAt)
      if (!previous) {
        setArchiveEnd(true)
        return
      }
      if (previous.publishedAt >= current.publishedAt) throw new Error('Brief archive returned an out-of-order result')
      setHistory((loaded) => [...loaded, previous])
      setIndex(index + 1)
    } catch {
      setArchiveError('Previous briefs could not be loaded.')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="brief-screen">
      {latest && (
        <BriefNavigation
          index={index}
          loading={loading}
          onNewer={() => { setArchiveError(undefined); setIndex(Math.max(0, index - 1)) }}
          onOlder={() => void openOlder()}
          olderDisabled={archiveEnd && !history[index + 1]}
        />
      )}
      {archiveError && (
        <Alert className="brief-archive-error" variant="destructive">
          <AlertTitle>Archive unavailable</AlertTitle>
          <AlertDescription>{archiveError}</AlertDescription>
        </Alert>
      )}
      {current
        ? <BriefIssue brief={current} onSymbol={onSymbol} />
        : (
            <section className="brief-empty">
              <h2>No brief yet</h2>
              <p>The first brief lands with the next trading morning's run.</p>
            </section>
          )}
      <ChannelArchiveScreen />
    </div>
  )
}
