import { useEffect, useRef, useState, type RefObject } from 'react'
import { ArrowUpRight, ChevronLeft, ChevronRight } from 'lucide-react'

import { Alert, AlertDescription, AlertTitle } from '#/components/ui/alert'
import { Button } from '#/components/ui/button'
import { Spinner } from '#/components/ui/spinner'
import { loadPreviousDailyBrief } from '../data/brief-archive'
import { type DailyBrief } from '../domain/brief'
import { RecommendationCard } from './brief-card'
import { formatCalendarDay, nyDateTime } from './ny-time'

function BriefNavigation({ index, loading, onNewer, onOlder, olderDisabled }: {
  index: number
  loading: boolean
  onNewer: () => void
  onOlder: () => void
  olderDisabled: boolean
}) {
  return (
    <nav aria-label="Brief archive" className="brief-navigation">
      {/* Busy rather than disabled while loading, and focusable when disabled: disabling the
          focused button would drop keyboard focus to the page. The handler ignores a press while
          a load is in flight. */}
      <Button
        aria-busy={loading}
        disabled={olderDisabled}
        focusableWhenDisabled
        onClick={onOlder}
        size="sm"
        type="button"
        variant="ghost"
      >
        {loading ? <Spinner data-icon="inline-start" /> : <ChevronLeft data-icon="inline-start" />}
        Previous
      </Button>
      <Button disabled={index === 0 || loading} focusableWhenDisabled onClick={onNewer} size="sm" type="button" variant="ghost">
        Next<ChevronRight data-icon="inline-end" />
      </Button>
    </nav>
  )
}

function BriefIssue({ brief, focusTarget, onSymbol }: {
  brief: DailyBrief
  focusTarget: RefObject<HTMLHeadingElement | null>
  onSymbol: (symbol: string) => void
}) {
  return (
    <>
      <header className="brief-cover">
        {/* The archive walks by market day, so the cover names that day; the publication instant
            is secondary, and can be later than a newer day's when an older issue is republished. */}
        <h2 className="brief-date" ref={focusTarget} tabIndex={-1}>
          <time dateTime={brief.marketDate}>{formatCalendarDay(brief.marketDate)}</time>
        </h2>
        <p className="brief-published">
          Published <time dateTime={brief.publishedAt}>{nyDateTime.format(new Date(brief.publishedAt))}</time>
        </p>
        <p className="brief-byline">Generated by <strong>{brief.model}</strong></p>
      </header>
      {brief.links.length > 0 && (
        <section aria-labelledby="brief-links-title" className="brief-links-section">
          <h2 id="brief-links-title">Reading</h2>
          <ol className="brief-links">
            {brief.links.map((link) => (
              <li key={link.url}>
                <a href={link.url} rel="noreferrer" target="_blank">
                  <span>{new URL(link.url).host}</span>{link.url}<ArrowUpRight aria-hidden="true" />
                </a>
              </li>
            ))}
          </ol>
        </section>
      )}
      <section aria-labelledby="brief-trades-title" className="brief-trades">
        <h2 id="brief-trades-title">{brief.recommendations.length ? 'Trades' : 'No trades'}</h2>
        {brief.recommendations.map((recommendation, index) => (
          <RecommendationCard key={`${recommendation.symbol}-${index}`} onSymbol={onSymbol} recommendation={recommendation} />
        ))}
        <p className="disclaimer">Not financial advice.</p>
      </section>
    </>
  )
}

/**
 * The latest brief with the archive behind it, one issue at a time. Nothing on the site
 * produces a brief: the private Workflow publishes it into the store this reads from.
 */
export function BriefScreen({ latest, onSymbol }: { latest?: DailyBrief; onSymbol: (symbol: string) => void }) {
  const [history, setHistory] = useState<DailyBrief[]>(() => latest ? [latest] : [])
  const [index, setIndex] = useState(0)
  const [archiveEnd, setArchiveEnd] = useState(!latest)
  const [archiveError, setArchiveError] = useState<string>()
  const [loading, setLoading] = useState(false)
  const current = history[index]
  // Moving between issues replaces the page under the reader, so focus follows to the new
  // issue's date rather than staying on a button that may now be disabled.
  const focusTarget = useRef<HTMLHeadingElement>(null)
  const [moved, setMoved] = useState(false)
  useEffect(() => {
    if (moved) focusTarget.current?.focus()
  }, [index, moved])

  const openOlder = async () => {
    if (loading) return
    if (history[index + 1]) {
      setIndex(index + 1)
      setMoved(true)
      return
    }
    if (!current) return
    setArchiveError(undefined)
    setLoading(true)
    try {
      const previous = await loadPreviousDailyBrief(current.marketDate)
      if (!previous) {
        setArchiveEnd(true)
        return
      }
      if (previous.marketDate >= current.marketDate) throw new Error('Brief archive returned an out-of-order result')
      setHistory((loaded) => [...loaded, previous])
      setIndex(index + 1)
      setMoved(true)
    } catch {
      setArchiveError('Previous briefs could not be loaded.')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="brief-screen">
      {latest && (
        <BriefNavigation
          index={index}
          loading={loading}
          onNewer={() => { setArchiveError(undefined); setIndex(Math.max(0, index - 1)); setMoved(true) }}
          onOlder={() => void openOlder()}
          olderDisabled={archiveEnd && !history[index + 1]}
        />
      )}
      {archiveError && (
        <Alert className="archive-error" variant="destructive">
          <AlertTitle>Archive unavailable</AlertTitle>
          <AlertDescription>{archiveError}</AlertDescription>
        </Alert>
      )}
      {current
        ? <BriefIssue brief={current} focusTarget={focusTarget} onSymbol={onSymbol} />
        : (
            <section className="brief-empty">
              <h2>No brief yet</h2>
              <p>The first brief lands with the next trading morning's run.</p>
            </section>
          )}
    </div>
  )
}
