/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiSnapshotRouteImport } from './routes/api.snapshot'
import { Route as ApiStreamRouteImport } from './routes/api.stream'
import { Route as ApiActionsActionIdRouteImport } from './routes/api.actions.$actionId'
import { Route as ApiCatalystsRefreshRouteImport } from './routes/api.catalysts.refresh'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSnapshotRoute = ApiSnapshotRouteImport.update({
  id: '/api/snapshot',
  path: '/api/snapshot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamRoute = ApiStreamRouteImport.update({
  id: '/api/stream',
  path: '/api/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiActionsActionIdRoute = ApiActionsActionIdRouteImport.update({
  id: '/api/actions/$actionId',
  path: '/api/actions/$actionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalystsRefreshRoute = ApiCatalystsRefreshRouteImport.update({
  id: '/api/catalysts/refresh',
  path: '/api/catalysts/refresh',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/api/snapshot': typeof ApiSnapshotRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/actions/$actionId': typeof ApiActionsActionIdRoute
  '/api/catalysts/refresh': typeof ApiCatalystsRefreshRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/api/snapshot': typeof ApiSnapshotRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/actions/$actionId': typeof ApiActionsActionIdRoute
  '/api/catalysts/refresh': typeof ApiCatalystsRefreshRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/api/snapshot': typeof ApiSnapshotRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/actions/$actionId': typeof ApiActionsActionIdRoute
  '/api/catalysts/refresh': typeof ApiCatalystsRefreshRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/api/health'
    | '/api/snapshot'
    | '/api/stream'
    | '/api/actions/$actionId'
    | '/api/catalysts/refresh'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/api/health'
    | '/api/snapshot'
    | '/api/stream'
    | '/api/actions/$actionId'
    | '/api/catalysts/refresh'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/api/health'
    | '/api/snapshot'
    | '/api/stream'
    | '/api/actions/$actionId'
    | '/api/catalysts/refresh'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiSnapshotRoute: typeof ApiSnapshotRoute
  ApiStreamRoute: typeof ApiStreamRoute
  ApiActionsActionIdRoute: typeof ApiActionsActionIdRoute
  ApiCatalystsRefreshRoute: typeof ApiCatalystsRefreshRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/snapshot': {
      id: '/api/snapshot'
      path: '/api/snapshot'
      fullPath: '/api/snapshot'
      preLoaderRoute: typeof ApiSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream': {
      id: '/api/stream'
      path: '/api/stream'
      fullPath: '/api/stream'
      preLoaderRoute: typeof ApiStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/actions/$actionId': {
      id: '/api/actions/$actionId'
      path: '/api/actions/$actionId'
      fullPath: '/api/actions/$actionId'
      preLoaderRoute: typeof ApiActionsActionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalysts/refresh': {
      id: '/api/catalysts/refresh'
      path: '/api/catalysts/refresh'
      fullPath: '/api/catalysts/refresh'
      preLoaderRoute: typeof ApiCatalystsRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiSnapshotRoute: ApiSnapshotRoute,
  ApiStreamRoute: ApiStreamRoute,
  ApiActionsActionIdRoute: ApiActionsActionIdRoute,
  ApiCatalystsRefreshRoute: ApiCatalystsRefreshRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
