/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthorizeRouteImport } from './routes/authorize'
import { Route as DisclosuresRouteImport } from './routes/disclosures'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiAgentConnectionRouteImport } from './routes/api.agent-connection'
import { Route as ApiFavoritesRouteImport } from './routes/api.favorites'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiMcpTokensRouteImport } from './routes/api.mcp-tokens'
import { Route as ApiPublicCatalystRefreshRouteImport } from './routes/api.public-catalyst-refresh'
import { Route as ApiPublicChannelArchiveRouteImport } from './routes/api.public-channel-archive'
import { Route as ApiPublicDailyRecommendationsRouteImport } from './routes/api.public-daily-recommendations'
import { Route as ApiPublicSnapshotRouteImport } from './routes/api.public-snapshot'
import { Route as ApiPublicSymbolEvidenceRouteImport } from './routes/api.public-symbol-evidence'
import { Route as ApiPublicSymbolSearchRouteImport } from './routes/api.public-symbol-search'
import { Route as ApiPublicYearCandlesRouteImport } from './routes/api.public-year-candles'
import { Route as ApiSnapshotRouteImport } from './routes/api.snapshot'
import { Route as ApiStreamRouteImport } from './routes/api.stream'
import { Route as ApiViewerRouteImport } from './routes/api.viewer'
import { Route as AuthorizeIndexRouteImport } from './routes/authorize.index'
import { Route as AuthorizeConsentRouteImport } from './routes/authorize.consent'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizeRoute = AuthorizeRouteImport.update({
  id: '/authorize',
  path: '/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclosuresRoute = DisclosuresRouteImport.update({
  id: '/disclosures',
  path: '/disclosures',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentConnectionRoute = ApiAgentConnectionRouteImport.update({
  id: '/api/agent-connection',
  path: '/api/agent-connection',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFavoritesRoute = ApiFavoritesRouteImport.update({
  id: '/api/favorites',
  path: '/api/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpTokensRoute = ApiMcpTokensRouteImport.update({
  id: '/api/mcp-tokens',
  path: '/api/mcp-tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCatalystRefreshRoute =
  ApiPublicCatalystRefreshRouteImport.update({
    id: '/api/public-catalyst-refresh',
    path: '/api/public-catalyst-refresh',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicChannelArchiveRoute = ApiPublicChannelArchiveRouteImport.update({
  id: '/api/public-channel-archive',
  path: '/api/public-channel-archive',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDailyRecommendationsRoute =
  ApiPublicDailyRecommendationsRouteImport.update({
    id: '/api/public-daily-recommendations',
    path: '/api/public-daily-recommendations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSnapshotRoute = ApiPublicSnapshotRouteImport.update({
  id: '/api/public-snapshot',
  path: '/api/public-snapshot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSymbolEvidenceRoute = ApiPublicSymbolEvidenceRouteImport.update({
  id: '/api/public-symbol-evidence',
  path: '/api/public-symbol-evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSymbolSearchRoute = ApiPublicSymbolSearchRouteImport.update({
  id: '/api/public-symbol-search',
  path: '/api/public-symbol-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicYearCandlesRoute = ApiPublicYearCandlesRouteImport.update({
  id: '/api/public-year-candles',
  path: '/api/public-year-candles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSnapshotRoute = ApiSnapshotRouteImport.update({
  id: '/api/snapshot',
  path: '/api/snapshot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamRoute = ApiStreamRouteImport.update({
  id: '/api/stream',
  path: '/api/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiViewerRoute = ApiViewerRouteImport.update({
  id: '/api/viewer',
  path: '/api/viewer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizeIndexRoute = AuthorizeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthorizeRoute,
} as any)
const AuthorizeConsentRoute = AuthorizeConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => AuthorizeRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authorize': typeof AuthorizeRouteWithChildren
  '/disclosures': typeof DisclosuresRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/api/agent-connection': typeof ApiAgentConnectionRoute
  '/api/favorites': typeof ApiFavoritesRoute
  '/api/health': typeof ApiHealthRoute
  '/api/mcp-tokens': typeof ApiMcpTokensRoute
  '/api/public-catalyst-refresh': typeof ApiPublicCatalystRefreshRoute
  '/api/public-channel-archive': typeof ApiPublicChannelArchiveRoute
  '/api/public-daily-recommendations': typeof ApiPublicDailyRecommendationsRoute
  '/api/public-snapshot': typeof ApiPublicSnapshotRoute
  '/api/public-symbol-evidence': typeof ApiPublicSymbolEvidenceRoute
  '/api/public-symbol-search': typeof ApiPublicSymbolSearchRoute
  '/api/public-year-candles': typeof ApiPublicYearCandlesRoute
  '/api/snapshot': typeof ApiSnapshotRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/viewer': typeof ApiViewerRoute
  '/authorize/consent': typeof AuthorizeConsentRoute
  '/authorize/': typeof AuthorizeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/disclosures': typeof DisclosuresRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/api/agent-connection': typeof ApiAgentConnectionRoute
  '/api/favorites': typeof ApiFavoritesRoute
  '/api/health': typeof ApiHealthRoute
  '/api/mcp-tokens': typeof ApiMcpTokensRoute
  '/api/public-catalyst-refresh': typeof ApiPublicCatalystRefreshRoute
  '/api/public-channel-archive': typeof ApiPublicChannelArchiveRoute
  '/api/public-daily-recommendations': typeof ApiPublicDailyRecommendationsRoute
  '/api/public-snapshot': typeof ApiPublicSnapshotRoute
  '/api/public-symbol-evidence': typeof ApiPublicSymbolEvidenceRoute
  '/api/public-symbol-search': typeof ApiPublicSymbolSearchRoute
  '/api/public-year-candles': typeof ApiPublicYearCandlesRoute
  '/api/snapshot': typeof ApiSnapshotRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/viewer': typeof ApiViewerRoute
  '/authorize/consent': typeof AuthorizeConsentRoute
  '/authorize': typeof AuthorizeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/authorize': typeof AuthorizeRouteWithChildren
  '/disclosures': typeof DisclosuresRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/api/agent-connection': typeof ApiAgentConnectionRoute
  '/api/favorites': typeof ApiFavoritesRoute
  '/api/health': typeof ApiHealthRoute
  '/api/mcp-tokens': typeof ApiMcpTokensRoute
  '/api/public-catalyst-refresh': typeof ApiPublicCatalystRefreshRoute
  '/api/public-channel-archive': typeof ApiPublicChannelArchiveRoute
  '/api/public-daily-recommendations': typeof ApiPublicDailyRecommendationsRoute
  '/api/public-snapshot': typeof ApiPublicSnapshotRoute
  '/api/public-symbol-evidence': typeof ApiPublicSymbolEvidenceRoute
  '/api/public-symbol-search': typeof ApiPublicSymbolSearchRoute
  '/api/public-year-candles': typeof ApiPublicYearCandlesRoute
  '/api/snapshot': typeof ApiSnapshotRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/viewer': typeof ApiViewerRoute
  '/authorize/consent': typeof AuthorizeConsentRoute
  '/authorize/': typeof AuthorizeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authorize'
    | '/disclosures'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/api/agent-connection'
    | '/api/favorites'
    | '/api/health'
    | '/api/mcp-tokens'
    | '/api/public-catalyst-refresh'
    | '/api/public-channel-archive'
    | '/api/public-daily-recommendations'
    | '/api/public-snapshot'
    | '/api/public-symbol-evidence'
    | '/api/public-symbol-search'
    | '/api/public-year-candles'
    | '/api/snapshot'
    | '/api/stream'
    | '/api/viewer'
    | '/authorize/consent'
    | '/authorize/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/disclosures'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/api/agent-connection'
    | '/api/favorites'
    | '/api/health'
    | '/api/mcp-tokens'
    | '/api/public-catalyst-refresh'
    | '/api/public-channel-archive'
    | '/api/public-daily-recommendations'
    | '/api/public-snapshot'
    | '/api/public-symbol-evidence'
    | '/api/public-symbol-search'
    | '/api/public-year-candles'
    | '/api/snapshot'
    | '/api/stream'
    | '/api/viewer'
    | '/authorize/consent'
    | '/authorize'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/authorize'
    | '/disclosures'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/api/agent-connection'
    | '/api/favorites'
    | '/api/health'
    | '/api/mcp-tokens'
    | '/api/public-catalyst-refresh'
    | '/api/public-channel-archive'
    | '/api/public-daily-recommendations'
    | '/api/public-snapshot'
    | '/api/public-symbol-evidence'
    | '/api/public-symbol-search'
    | '/api/public-year-candles'
    | '/api/snapshot'
    | '/api/stream'
    | '/api/viewer'
    | '/authorize/consent'
    | '/authorize/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthorizeRoute: typeof AuthorizeRouteWithChildren
  DisclosuresRoute: typeof DisclosuresRoute
  PrivacyRoute: typeof PrivacyRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  ApiAgentConnectionRoute: typeof ApiAgentConnectionRoute
  ApiFavoritesRoute: typeof ApiFavoritesRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiMcpTokensRoute: typeof ApiMcpTokensRoute
  ApiPublicCatalystRefreshRoute: typeof ApiPublicCatalystRefreshRoute
  ApiPublicChannelArchiveRoute: typeof ApiPublicChannelArchiveRoute
  ApiPublicDailyRecommendationsRoute: typeof ApiPublicDailyRecommendationsRoute
  ApiPublicSnapshotRoute: typeof ApiPublicSnapshotRoute
  ApiPublicSymbolEvidenceRoute: typeof ApiPublicSymbolEvidenceRoute
  ApiPublicSymbolSearchRoute: typeof ApiPublicSymbolSearchRoute
  ApiPublicYearCandlesRoute: typeof ApiPublicYearCandlesRoute
  ApiSnapshotRoute: typeof ApiSnapshotRoute
  ApiStreamRoute: typeof ApiStreamRoute
  ApiViewerRoute: typeof ApiViewerRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authorize': {
      id: '/authorize'
      path: '/authorize'
      fullPath: '/authorize'
      preLoaderRoute: typeof AuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclosures': {
      id: '/disclosures'
      path: '/disclosures'
      fullPath: '/disclosures'
      preLoaderRoute: typeof DisclosuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent-connection': {
      id: '/api/agent-connection'
      path: '/api/agent-connection'
      fullPath: '/api/agent-connection'
      preLoaderRoute: typeof ApiAgentConnectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/favorites': {
      id: '/api/favorites'
      path: '/api/favorites'
      fullPath: '/api/favorites'
      preLoaderRoute: typeof ApiFavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp-tokens': {
      id: '/api/mcp-tokens'
      path: '/api/mcp-tokens'
      fullPath: '/api/mcp-tokens'
      preLoaderRoute: typeof ApiMcpTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public-catalyst-refresh': {
      id: '/api/public-catalyst-refresh'
      path: '/api/public-catalyst-refresh'
      fullPath: '/api/public-catalyst-refresh'
      preLoaderRoute: typeof ApiPublicCatalystRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public-channel-archive': {
      id: '/api/public-channel-archive'
      path: '/api/public-channel-archive'
      fullPath: '/api/public-channel-archive'
      preLoaderRoute: typeof ApiPublicChannelArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public-daily-recommendations': {
      id: '/api/public-daily-recommendations'
      path: '/api/public-daily-recommendations'
      fullPath: '/api/public-daily-recommendations'
      preLoaderRoute: typeof ApiPublicDailyRecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public-snapshot': {
      id: '/api/public-snapshot'
      path: '/api/public-snapshot'
      fullPath: '/api/public-snapshot'
      preLoaderRoute: typeof ApiPublicSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public-symbol-evidence': {
      id: '/api/public-symbol-evidence'
      path: '/api/public-symbol-evidence'
      fullPath: '/api/public-symbol-evidence'
      preLoaderRoute: typeof ApiPublicSymbolEvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public-symbol-search': {
      id: '/api/public-symbol-search'
      path: '/api/public-symbol-search'
      fullPath: '/api/public-symbol-search'
      preLoaderRoute: typeof ApiPublicSymbolSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public-year-candles': {
      id: '/api/public-year-candles'
      path: '/api/public-year-candles'
      fullPath: '/api/public-year-candles'
      preLoaderRoute: typeof ApiPublicYearCandlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/snapshot': {
      id: '/api/snapshot'
      path: '/api/snapshot'
      fullPath: '/api/snapshot'
      preLoaderRoute: typeof ApiSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream': {
      id: '/api/stream'
      path: '/api/stream'
      fullPath: '/api/stream'
      preLoaderRoute: typeof ApiStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/viewer': {
      id: '/api/viewer'
      path: '/api/viewer'
      fullPath: '/api/viewer'
      preLoaderRoute: typeof ApiViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authorize/': {
      id: '/authorize/'
      path: '/'
      fullPath: '/authorize/'
      preLoaderRoute: typeof AuthorizeIndexRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/authorize/consent': {
      id: '/authorize/consent'
      path: '/consent'
      fullPath: '/authorize/consent'
      preLoaderRoute: typeof AuthorizeConsentRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthorizeRouteChildren {
  AuthorizeConsentRoute: typeof AuthorizeConsentRoute
  AuthorizeIndexRoute: typeof AuthorizeIndexRoute
}

const AuthorizeRouteChildren: AuthorizeRouteChildren = {
  AuthorizeConsentRoute: AuthorizeConsentRoute,
  AuthorizeIndexRoute: AuthorizeIndexRoute,
}

const AuthorizeRouteWithChildren = AuthorizeRoute._addFileChildren(
  AuthorizeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthorizeRoute: AuthorizeRouteWithChildren,
  DisclosuresRoute: DisclosuresRoute,
  PrivacyRoute: PrivacyRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  ApiAgentConnectionRoute: ApiAgentConnectionRoute,
  ApiFavoritesRoute: ApiFavoritesRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiMcpTokensRoute: ApiMcpTokensRoute,
  ApiPublicCatalystRefreshRoute: ApiPublicCatalystRefreshRoute,
  ApiPublicChannelArchiveRoute: ApiPublicChannelArchiveRoute,
  ApiPublicDailyRecommendationsRoute: ApiPublicDailyRecommendationsRoute,
  ApiPublicSnapshotRoute: ApiPublicSnapshotRoute,
  ApiPublicSymbolEvidenceRoute: ApiPublicSymbolEvidenceRoute,
  ApiPublicSymbolSearchRoute: ApiPublicSymbolSearchRoute,
  ApiPublicYearCandlesRoute: ApiPublicYearCandlesRoute,
  ApiSnapshotRoute: ApiSnapshotRoute,
  ApiStreamRoute: ApiStreamRoute,
  ApiViewerRoute: ApiViewerRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
